export const FETCH_COUNTRIES_REQUEST = "FETCH_COUNTRIES_REQUEST";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE";
export const SEARCHED_TEXT = "SEARCHED_TEXT";
export const SEARCH_COUNTRIES_LIST = "SEARCH_COUNTRIES_LIST";
export const FILTER_COUNTRY_LIST = "FILTER_COUNTRY_LIST";
export const SEARCH_FILTER_COUNTRY_LIST = "SEARCH_FILTER_COUNTRY_LIST";
export const RESTORE_FAVOURITE_COUNTRY = "RESTORE_FAVOURITE_COUNTRY";
